# EDA of credit card data

Let's start by importing the necessary libraries. For this eda we will import numpy, pandas, matplotlb and seaborn.

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Now lets work on importing the data from the excel file using pandas. we will store this data in a pandas Data Frame. We will also see 5 random data points of this dataset.

In [8]:
data = pd.read_excel("default of credit card clients.xls")
data.sample(5)

,Unnamed: 0,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X15,X16,X17,X18,X19,X20,X21,X22,X23,Y
471,471,390000,2,3,2,35,0,0,0,0,...,252195,257496,263018,13802,16525,8893,9229,10000,9435,1
11648,11648,100000,1,2,2,26,0,0,0,0,...,98232,97752,0,10000,43000,5000,3000,0,0,0
19396,19396,140000,2,1,2,32,0,-1,0,0,...,19573,11611,0,32172,1476,2140,1000,0,0,0
19733,19733,120000,2,2,1,32,0,0,0,0,...,38500,38955,39926,1586,1616,1937,1392,1596,1684,0
4827,4827,60000,2,1,2,34,1,-2,-1,-1,...,0,0,11688,0,15798,0,0,11688,0,0

As you can see the data columns aren't clear. We will name them properly before doing anything else.

In [9]:
data.columns = ['ID','LIMIT_BAL','SEX','EDUCATION','MARRIAGE','AGE','PAY_0','PAY_2','PAY_3','PAY_4',	'PAY_5','PAY_6','BILL_AMT1','BILL_AMT2','BILL_AMT3','BILL_AMT4','BILL_AMT5','BILL_AMT6','PAY_AMT1',	'PAY_AMT2','PAY_AMT3','PAY_AMT4','PAY_AMT5','PAY_AMT6','default payment next month'
]
data.sample(5)

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
18781,18781,400000,2,1,2,29,-1,-1,-2,-2,...,0,0,0,95,0,0,0,0,0,0
14397,14397,420000,2,2,1,40,0,0,0,2,...,38022,20256,22743,5900,900,101,3000,3000,5000,0
12684,12684,200000,2,2,2,33,0,0,0,0,...,-387,-387,-387,1917,1000,0,0,0,0,0
1836,1836,50000,2,2,2,37,1,2,2,2,...,16684,18017,17581,0,4000,0,1600,0,3000,1
4317,4317,10000,1,3,2,24,0,0,0,0,...,8544,9858,1303,2000,2000,2000,2000,1000,0,0

This is much more better. now as Id columns is useless, lets drop it.

In [10]:
data = data.drop(columns = 'ID')
data.sample(5)

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
5,50000,1,2,1,57,-1,0,-1,0,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0
21133,500000,1,1,2,35,-2,-2,-2,-2,-2,...,5086,9552,14389,11194,21193,5094,9563,14403,5233,0
7486,30000,2,2,1,27,0,0,2,2,2,...,24872,25427,25860,3300,1000,1000,1100,1000,1100,1
5828,280000,2,1,2,38,-1,0,0,-1,0,...,13139,13989,15559,2000,30000,14000,1000,16000,0,1
16443,90000,2,2,1,50,0,0,0,2,0,...,46615,47537,48616,2100,4200,0,2000,2000,2000,0

Now let's understand the meaning of the features. After researching, I found that