# EDA of credit card data

Let's start by importing the necessary libraries. For this eda we will import numpy, pandas, matplotlb and seaborn.

In [30]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

Now lets work on importing the data from the excel file using pandas. we will store this data in a pandas Data Frame. We will also see 5 random data points of this dataset.

In [37]:
data = pd.read_excel("default of credit card clients.xls", header = 1)
data.sample(5)

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
11132,11133,50000,2,2,1,39,1,-2,-2,-1,...,2219,390,390,0,0,2219,390,390,390,0
8291,8292,50000,2,2,2,28,0,0,0,0,...,25542,26160,26686,1468,1400,900,1000,1000,600,0
13795,13796,180000,1,2,1,49,-1,-1,-1,-1,...,660,36906,1470,660,660,660,36906,1320,0,0
2159,2160,220000,1,1,1,54,-2,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
13598,13599,190000,2,2,1,33,1,-2,-2,-2,...,-3000,-3000,-3000,0,0,0,0,0,0,0

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
20578,20579,100000,1,2,1,29,0,0,0,0,...,57079,16634,26438,2303,3000,3000,1000,10022,3065,0
9962,9963,20000,1,2,2,55,2,2,2,2,...,0,0,0,780,0,0,0,0,0,0
24984,24985,50000,1,3,0,39,0,0,0,0,...,25791,19476,19066,1710,1787,1295,825,684,784,0
7745,7746,80000,1,2,1,54,0,0,0,0,...,22460,22743,22988,1500,3901,1001,1001,1001,1901,0
21633,21634,30000,2,5,2,22,0,0,0,0,...,14500,0,0,1859,1232,1040,0,0,0,1

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
26663,26664,60000,1,2,2,27,5,4,3,2,...,61769,51722,44956,0,0,0,51722,16000,1100,1
9435,9436,80000,1,3,2,43,2,2,0,0,...,12577,18376,23766,3006,5250,33,18431,23944,28457,0
22053,22054,50000,2,3,2,29,0,0,0,0,...,7464,42705,43662,1840,1311,2000,42705,1569,2822,0
14208,14209,120000,1,1,2,28,0,0,0,0,...,40107,41464,42680,3700,1640,2000,2000,2000,1800,0
27724,27725,30000,2,3,2,24,1,-2,-1,0,...,2432,827,0,0,1469,1008,300,0,0,0

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
14459,14460,140000,2,2,2,35,0,0,0,0,...,84455,87287,81423,5509,7124,2866,4033,5954,3120,0
4770,4771,200000,2,2,2,31,1,-2,-2,-1,...,1500,0,0,0,0,1500,0,0,0,0
23464,23465,20000,2,2,1,32,0,0,0,2,...,11954,14750,14371,2000,2400,600,3000,0,600,1
11667,11668,30000,2,2,1,26,0,0,0,0,...,28501,29687,29497,1600,1500,1000,4000,1900,0,0
16575,16576,20000,1,2,2,24,0,0,0,0,...,19079,19060,19061,3287,1313,1299,670,686,694,0

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
14557,14558,200000,1,1,1,39,0,0,0,0,...,185049,188375,183069,6500,8051,13000,6500,0,6700,0
8108,8109,160000,2,1,2,40,1,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
3293,3294,30000,1,1,2,23,0,0,0,0,...,30106,30318,28985,1507,5538,1030,1500,1500,1500,0
29993,29994,100000,1,1,2,38,0,-1,-1,0,...,70626,69473,55004,2000,111784,4000,3000,2000,2000,0
19291,19292,120000,2,2,2,39,-2,-2,-2,-2,...,326,326,476,3756,652,326,326,476,326,1

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
12412,12413,50000,2,2,2,26,-1,-1,-1,-1,...,0,0,0,0,2525,0,0,0,0,0
10638,10639,310000,2,2,2,24,0,0,0,0,...,139275,120762,102598,6373,5600,5000,4500,3500,2816,0
6186,6187,200000,1,1,2,33,-2,-2,-2,-2,...,-18,-18,-18,0,0,0,0,0,0,1
18412,18413,50000,2,2,2,25,0,0,0,0,...,48803,19324,19668,1800,2100,2600,1000,1000,1000,0
5551,5552,20000,1,2,1,40,1,2,2,0,...,16604,16837,17357,1570,0,800,650,800,1000,0

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
21507,21508,20000,2,2,2,22,3,4,3,2,...,20334,19943,19956,0,0,0,458,463,235,1
20444,20445,140000,1,2,2,28,0,0,0,0,...,76564,139508,142253,5000,6614,2198,140000,5413,4689,0
24287,24288,200000,1,1,2,32,0,0,0,-2,...,0,0,0,5005,0,0,0,0,2842,0
23429,23430,500000,2,1,2,28,-2,-2,-2,-2,...,3963,3418,858,0,0,3994,3435,860,0,0
9652,9653,300000,2,2,1,26,-1,-1,-1,-1,...,316,316,466,316,316,316,316,466,316,0

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
17969,17970,50000,1,2,1,34,0,0,0,0,...,46165,10142,10825,2000,3000,2200,1200,1000,1000,0
27856,27857,70000,2,2,2,22,0,0,0,0,...,34685,30166,29299,2049,1700,1446,1000,1044,1176,0
16350,16351,50000,2,2,1,31,2,0,0,2,...,46993,47940,50903,1724,3855,0,1694,3713,2000,0
843,844,110000,2,2,2,33,1,-2,-2,-2,...,0,0,150,0,0,0,0,300,102,1
15977,15978,80000,2,2,1,38,0,0,0,0,...,40128,41152,41527,3133,2132,1650,2000,1503,1505,0

As you can see the data columns aren't clear. We will name them properly before doing anything else.

This is much more better. now as Id columns is useless, lets drop it.

In [39]:
data = data.drop(columns = 'ID')
data.sample(5)

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
18683,200000,2,1,2,27,1,-2,-2,-2,-1,...,0,3012,3021,0,0,0,3012,9,363,0
4988,130000,2,2,1,32,1,2,0,0,0,...,52076,55432,56571,0,2500,2000,4200,2200,0,1
8743,240000,2,1,2,38,0,0,0,0,0,...,186168,166745,165582,7000,10000,10000,10000,5000,10000,0
14486,110000,1,3,1,45,0,0,0,0,0,...,38935,40633,41393,4400,3900,3900,4000,3100,1600,0
5526,390000,1,1,1,33,0,0,0,0,0,...,32711,36215,40650,6000,5000,5000,4000,5000,8883,0

KeyError: "['ID'] not found in axis"

In [ ]:
data.describe()

Now let's understand the meaning of the features. After researching, I found that :
- LIMIT_BAL: Amount of the given credit (in NT dollars).
- SEX: Gender (1 = male; 2 = female).
- EDUCATION: Education level (1 = graduate school; 2 = university; 3 = high school; 4 = others; 0, 5, 6 are often grouped into "others/unknown").
- MARRIAGE: Marital status (1 = married; 2 = single; 3 = others).
- AGE: Age in years.
- PAY_0 (or PAY_1), PAY_2, PAY_3, PAY_4, PAY_5, PAY_6: Repayment status for each of the last six months. The values indicate the payment delay:
  - -1 = Pay duly/on time.
  - 0 = No delay.
  - 1 = Payment delay for one month.
  - 2 = Payment delay for two months, etc., up to 9 (nine months and above delay).
- BILL_AMT1 to BILL_AMT6: Amount of bill statement for each of the last six months.
- PAY_AMT1 to PAY_AMT6: Amount of previous payment for each of the last six months.

Now as we know what every feature is, we can explore the data more properly.
Before exploring any feature, lets see if there are any missing values.

In [ ]:
data.isna().sum()

There seems to be no missing data!

In [ ]:
sns.heatmap(data.corr())
plt.show()

In [ ]:
print(data.skew(axis = 0))

In [ ]:
sns.barplot(x = 'default payment next month', y = 'default payment next month',  data = data, estimator = len)
plt.show()

In [ ]:
sns.histplot(x = 'LIMIT_BAL', data = data, kde = True, bins = 50)
plt.show()

In [ ]:
sns.boxplot(y = 'LIMIT_BAL',x = 'default payment next month', data = data)
plt.show()

In [ ]:
sns.barplot(x = "SEX", y = "default payment next month", data = data, estimator = len)
plt.show()

In [ ]:
sns.barplot(x = "EDUCATION", y = "default payment next month", data = data, estimator = len)
plt.show()

In [ ]:
data.hist(figsize=(30, 24), bins=50,layout=(5,5))
plt.show()

In [ ]:
data["EDUCATION"].value_counts()/len(data["EDUCATION"])

In [ ]:
sns.barplot(x = 'PAY_0', y = 'PAY_0',  data = data, estimator = len)
plt.show()

In [ ]:
from sklearn.base import BaseEstimator, TransformerMixin
import numpy as np
import pandas as pd

class FeatureEngineering(BaseEstimator, TransformerMixin):

    def __init__(self):
        self.feature_names_out_ = None
        self.X = None
        self.y = None

    def _slope(self, row):
        return np.polyfit(range(len(row)), row, 1)[0]

    def _add_features(self, X):
        X = X.copy()
        # -----------------------
        # DELAY FEATURES
        # -----------------------
        delay_cols = ["PAY_0","PAY_2","PAY_3","PAY_4","PAY_5","PAY_6"]
        X["delay_sum"] = X[delay_cols].sum(axis=1)
        X["max_delay"] = X[delay_cols].max(axis=1)
        X["delay_mean"] = X[delay_cols].mean(axis=1)
        X["delay_std"]  = X[delay_cols].std(axis=1)
        X["delay_trend"] = X[delay_cols].apply(self._slope, axis=1)

        # -----------------------
        # BILL FEATURES
        # -----------------------
        bill_cols = ["BILL_AMT1","BILL_AMT2","BILL_AMT3","BILL_AMT4","BILL_AMT5","BILL_AMT6"]
        X["bill_trend"] = X[bill_cols].apply(self._slope, axis=1)
        X["bill_vol"] = X[bill_cols].std(axis=1)

        # utilization
        X["util1"] = X["BILL_AMT1"] / (X["LIMIT_BAL"] + 1)
        X["util6"] = X["BILL_AMT6"] / (X["LIMIT_BAL"] + 1)
        X["util_trend"] = X[["util1","util6"]].apply(self._slope, axis=1)
        X["util_diff"] = X["util6"] - X["util1"]  # increase = risky

        # -----------------------
        # PAYMENT AMOUNT FEATURES
        # -----------------------
        pay_amt_cols = ["PAY_AMT1","PAY_AMT2","PAY_AMT3","PAY_AMT4","PAY_AMT5","PAY_AMT6"]
        X["pay_amt_trend"] = X[pay_amt_cols].apply(self._slope, axis=1)
        X["pay_vol"] = X[pay_amt_cols].std(axis=1)


        # -----------------------
        # MIXED INTERACTION FEATURES
        # -----------------------
        X["AGE_x_LIMIT_BAL"] = X["AGE"] * X["LIMIT_BAL"]

        top_pairs = [
              ("LIMIT_BAL", "BILL_AMT1"),
            ("LIMIT_BAL", "AGE"),
            ("LIMIT_BAL", "PAY_AMT3"),
            ("LIMIT_BAL", "PAY_AMT6"),
            ("PAY_0", "BILL_AMT1"),
            ("LIMIT_BAL", "PAY_AMT1"),
            ("LIMIT_BAL", "PAY_AMT2"),
            ("LIMIT_BAL", "PAY_AMT4"),
            ("LIMIT_BAL", "PAY_0"),
            ("PAY_0", "PAY_2")
        ]

        for f1, f2 in top_pairs:
            X[f"{f1}_x_{f2}"] = X[f1] * X[f2]
        print(X.isna().sum())
        print((X == float('inf')).sum())
        return X

    def fit(self, X, y=None):
        X_temp = self._add_features(X)
        self.feature_names_out_ = X_temp.columns.tolist()
        self.X = X_temp
        self.y = y
        return self

    def transform(self, X, y=None):
        X_transformed = self._add_features(X)
        return X_transformed

    def get_feature_names_out(self, input_features=None):
        return np.array(self.feature_names_out_, dtype=object)

    def get_train(self):
        print(self.X, self.y)
        return self.X, self.y

In [ ]:
TOTAL_DATA_POINTS = 30000
TRAIN_RATIO = 0.85
VAL_RATIO = 0
TEST_RATIO = 0.15
TRAIN_POINTS = int(TOTAL_DATA_POINTS * TRAIN_RATIO)
TEST_POINTS = int(TOTAL_DATA_POINTS * TEST_RATIO)
VAL_RATIO = int(TOTAL_DATA_POINTS * VAL_RATIO)

In [ ]:
train = data[:TRAIN_POINTS]
test = data[TRAIN_POINTS:TRAIN_POINTS+TEST_POINTS]
val = data[TRAIN_POINTS+TEST_POINTS:]

X_train = train.drop(columns="default payment next month")
y_train = train["default payment next month"]

X_test = test.drop(columns="default payment next month")
y_test = test["default payment next month"]

X_val = val.drop(columns="default payment next month")
y_val = val["default payment next month"]

In [ ]:
from imblearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from catboost import CatBoostClassifier
from xgboost import XGBClassifier
from imblearn.over_sampling import SMOTE, RandomOverSampler
from sklearn.preprocessing import MinMaxScaler

In [ ]:
model = Pipeline([
    ('feature_engineer', FeatureEngineering()),
    ('scaler', MinMaxScaler()),
    ('over_sampler', SMOTE()),
    ('classifier', XGBClassifier(use_label_encoder = False,scale_pos_weight=len(y_train[y_train == 1])/len(y_train[y_train == 0]), learning_rate=0.1, n_estimators=1000, max_depth = 3, eval_metric = 'mlogloss'))
])

In [ ]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, precision_recall_fscore_support
from catboost import Pool
model.fit(X_train, y_train)
preds = model.predict(X_test)

In [ ]:
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import average_precision_score
import matplotlib.pyplot as plt

y_scores = model.predict_proba(X_test)[:, 1]

precision, recall, thresholds = precision_recall_curve(y_test, y_scores)

plt.figure(figsize=(7, 6))
plt.plot(recall, precision, linewidth=2)
plt.xlabel('Recall')
plt.ylabel('Precision')
plt.title('Precision-Recall Curve')
plt.grid(True)
plt.show()

# Optional: Print AP score (area under PR curve)
ap = average_precision_score(y_test, y_scores)
print("Average Precision Score:", ap)

In [ ]:
from sklearn.metrics import roc_auc_score
y_test_proba = model.predict_proba(X_test)[:, 1]
score = roc_auc_score(y_test, y_test_proba)
print(score)

In [ ]:
from sklearn.metrics import f1_score, precision_recall_curve, roc_auc_score
import numpy as np

prec, rec, thr = precision_recall_curve(y_test, y_test_proba)
f1 = 2 * (prec * rec) / (prec + rec)

best_idx = np.nanargmax(f1)
print("Best threshold:", thr[best_idx])
print("Best F1:", f1[best_idx])
print("Precision:", prec[best_idx])
print("Recall:", rec[best_idx])
print(roc_auc_score(y_test, y_test_proba))

In [ ]:
from sklearn.metrics import roc_curve

fpr, tpr, _ = roc_curve(y_test, y_test_proba)

plt.plot(fpr, tpr, linewidth=2)
plt.title('ROC curve')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.show()

In [ ]:
classifier = model.named_steps['classifier']
importance = classifier.feature_importances_
features = model[:-1].get_feature_names_out()
df = pd.DataFrame({'importance': importance, 'features': features})
df = df.sort_values('importance', ascending = False)
plt.figure(figsize=(10, 5))
plt.bar(df['features'][:10], df['importance'][:10])

In [ ]:
from sklearn.metrics import auc

print(auc(rec, prec))